name: Build and test the Docker image

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build . --file Dockerfile --tag ${{ env.PROJECT_NAME }}
      - name: Test
        run: docker run --env CI=true --name ${{ env.PROJECT_NAME }} ${{ env.PROJECT_NAME }} /tmp/tests/run.sh
