name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Parse semver tag
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{github.ref_name}}
      - name: If it's a pre-release
        run: |
          if [ -z ${{ steps.semver_parser.outputs.prerelease }} ]; then
            IS_PRERELEASE=""
            echo "IS_PRERELEASE=" >> $GITHUB_ENV
          else
            echo "IS_PRERELEASE= -p " >> $GITHUB_ENV
          fi
      - name: Create a release
        run: |
          gh release create ${{ steps.semver_parser.outputs.fullversion }} ${{ env.IS_PRERELEASE }} -R ${{github.repository}} --generate-notes -t "Release ${{github.ref_name}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
